
name: Deploy API to Production Slot

on:
  push:
    branches: [main]
  
  workflow_dispatch:
    branches: [main]

env:
  IMAGE_NAME: dabblefox-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get and format date of the latest commit
        run: |
          COMMIT_DATE=$(git log -1 --format=%ci)  # Get commit date in ISO 8601 format
          FORMATTED_DATE=$(date -d "$COMMIT_DATE" +"%Y%m%d%H%M%S")
          echo "FORMATTED_COMMIT_DATE=$FORMATTED_DATE" >> $GITHUB_ENV

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build, tag, and push image to ACR
        run: |
          docker build . -t ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.FORMATTED_COMMIT_DATE }}
          docker push ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.FORMATTED_COMMIT_DATE }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
    
      - name: Create Deployment Slot
        run: |
          SLOT_NAME="${{ env.FORMATTED_COMMIT_DATE }}"
          APP_NAME="${{ secrets.APP_NAME }}"
          RESOURCE_GROUP="${{ secrets.RESOURCE_GROUP }}"
          KEY_VAULT_NAME="${{ secrets.KEY_VAULT_NAME }}"
          VNET="${{ secrets.VNET }}"
          SUBNET="${{ secrets.SUBNET }}"
          az webapp deployment slot create --name $APP_NAME --resource-group $RESOURCE_GROUP --slot $SLOT_NAME
          az webapp vnet-integration add --name $APP_NAME --resource-group $RESOURCE_GROUP --slot $SLOT_NAME --vnet $VNET --subnet $SUBNET
          echo "Added VNet Integration"
          az webapp config appsettings set --name $APP_NAME --resource-group $RESOURCE_GROUP --slot $SLOT_NAME --settings DB_CONNECTION_URI="@Microsoft.KeyVault(SecretUri=https://$KEY_VAULT_NAME.vault.azure.net/secrets/DBConnectionURI)"
          az webapp config appsettings set --name $APP_NAME --resource-group $RESOURCE_GROUP --slot $SLOT_NAME --settings DB_NAME="@Microsoft.KeyVault(SecretUri=https://$KEY_VAULT_NAME.vault.azure.net/secrets/DBName)"
          echo "Added application settings to the App Service Slot"
          az webapp identity assign --name $APP_NAME --resource-group $RESOURCE_GROUP --slot $SLOT_NAME
          echo "Assigned a managed identity to the App Service Slot"
          echo "APP_OBJECT_ID=$(az webapp identity show --name $APP_NAME --resource-group $RESOURCE_GROUP --slot $SLOT_NAME --query principalId -o tsv)" >> $GITHUB_ENV
          echo "Deployment slot created: $APP_NAME-$SLOT_NAME"

      - name: Update Key Vault Access Policy
        run: |
          az keyvault set-policy --name ${{ secrets.KEY_VAULT_NAME }} --object-id ${{ env.APP_OBJECT_ID }} --secret-permissions get list
          echo "Key Vault access policy updated for ${{ secrets.APP_NAME }}-${{ env.FORMATTED_COMMIT_DATE }}"

      - name: Deploy New Image from ACR to New Slot
        run: |
          az webapp config container set \
          --name ${{ secrets.APP_NAME }}  \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --slot ${{ env.FORMATTED_COMMIT_DATE }} \
          --docker-custom-image-name ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.FORMATTED_COMMIT_DATE }} \
          --docker-registry-server-url https://${{ secrets.REGISTRY }} \
          --docker-registry-server-user ${{ secrets.REGISTRY_USERNAME }} \
          --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }}
