
name: Deploy to Azure Container Registry (ACR)

on:
  push:
    branches: [dev]
  
  workflow_dispatch:
    branches: [dev]

env:
  #REGISTRY: dabblefox${{ github.ref }}.azurecr.io
  REGISTRY: dabblefoxdev.azurecr.io
  IMAGE_NAME: dabblefox
  TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    # environment: ${{ github.ref }}
    environment: dev

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Deploy to Azure Container Registry
        run: |
          docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
