
name: Deploy API to ACR

on:
  push:
    branches: [dev, staging, main]
  
  workflow_dispatch:
    branches: [dev, staging, main]

env:
  IMAGE_NAME: dabblefox-api
  TAG: ${{ github.sha }}

jobs:
  determine-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}

    steps:
      - name: Determine Environment
        id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          else
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi

  build-and-deploy:
    needs: determine-env
    runs-on: ubuntu-latest
    environment: ${{ needs.determine-env.outputs.environment }}

    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3

#      - name: Login to ACR
#        uses: azure/docker-login@v1
#        with:
#          login-server: ${{ vars.REGISTRY }}
#          username: ${{ secrets.REGISTRY_USERNAME }}
#          password: ${{ secrets.REGISTRY_PASSWORD }}
#
#      - name: Build, tag, and push image to ACR
#        run: |
#          docker build . -t ${{ vars.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
#          docker push ${{ vars.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

#      - name: Deploy to Azure App Service
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: ${{ vars.APP_NAME }}
#          #slot-name: 'production' # Change this if you have different slots
#          #publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
#          images: ${{ vars.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Logout of Azure
        run: az logout

